### ISSUE TITLE
WINGET NOT INSTALLING

### ISSUE THREAD

**Issue by skyshines** [asheroto/winget-install#14]
PS E:\Documents\scripts> winget-install.ps1

##########################################
# Downloading & installing x64 VCLibs... #
##########################################

##########################################
# Downloading & installing x64 VCLibs... #
##########################################

URL: https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx

###########################################
# Downloading & installing x64 UI.Xaml... #
###########################################

Downloading: https://www.nuget.org/api/v2/package/Microsoft.UI.Xaml/2.7.3
Saving as: C:\Users\Akashdeep\AppData\Local\Temp\Microsoft.UI.Xaml.2.7.3.nupkg

###################################################
# WARNING! An error occurred during installation! #
###################################################

WARNING: Something went wrong. If messages above don't help and the problem persists,
WARNING: Please open an issue at https://github.com/asheroto/winget-install/issues
WARNING: Line number : 375
WARNING: Error: Unable to connect to the remote server

**Comment by asheroto** [comment]
This may have been a temporary issue, it appears to be working right now.

I have seen this happen quite often with nuget.org. The server seems to be finicky.

Can you please try again and see if it's working?

**Comment by asheroto** [comment]
I'm working on an alternate version with a backup URL. If you can't get it to work try this one:
https://github.com/asheroto/winget-install/blob/Alternate-Method/winget-install.ps1

**Comment by asheroto** [comment]
Releasing version `2.1.0` which should resolve this by adding an alternate download URL.
