### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Lukey222** [asheroto/winget-install#16]
# WARNING! An error occurred during installation! #
###################################################

WARNING: Something went wrong. If messages above don't help and the problem persists,
WARNING: Please open an issue at https://github.com/asheroto/winget-install/issues
WARNING: Line number : 434
WARNING: Error: Deployment failed with HRESULT: 0x80073CF6, Package could not be registered.

error 0xC0020036: windows.licensing failed to start ClipSvc. Try again and contact the package publisher if the problem
 persists.

NOTE: For additional information, look for [ActivityId] 6531d6de-ce87-000a-5ee3-3e6587ced901 in the Event Log or use
the command line Get-AppPackageLog -ActivityID 6531d6de-ce87-000a-5ee3-3e6587ced901

**Comment by asheroto** [comment]
What OS version and edition are you using?

**Comment by asheroto** [comment]
You might need this fix, not sure. Not an issue with this script but with the winget installation or ClipSvc itself. Try installing winget manually and you should see the same error. I'll go ahead and close this for now. If the issue only occurs in this script, let me know.

https://www.thewindowsclub.com/how-to-enable-clipsvc
