### ISSUE TITLE
No applicable app licenses found

### ISSUE THREAD

**Issue by Lars-Jensen** [asheroto/winget-install#17]
When installing on a new Windows 2022 server the installation completes successfully, but winget will not run.

The issue seems to be caused by a missing license file:
![image](https://github.com/asheroto/winget-install/assets/65961291/1ed83638-6738-4288-bfa0-c026516dc35f)

The issue has earlier been reported in winget repo:
https://github.com/microsoft/winget-cli/issues/700

The issue seems to be caused by the change where the script now uses **Add-AppxPackage** instead of **Add-AppxProvisionedPackage**:
https://github.com/asheroto/winget-install/blob/e4ffa763693d370757911f93d297e62fda61d776/winget-install.ps1#L442

**Add-AppxPackage** doesn't support adding a license file.
The PowerShell script only downloads the license file from Winget but never uses it.

I have locally changed the above mentioned line to:
Add-AppxProvisionedPackage -Online -PackagePath $wingetPath -LicensePath $wingetLicensePath -ErrorAction SilentlyContinue

and it works on the server I tested on

**Comment by asheroto** [comment]
Thanks, I hadn't run across this yet. I will do some testing and update the script.

**Comment by asheroto** [comment]
Releasing version `2.1.0` which will resolve this and add alternate method in case nuget isn't working.
