### ISSUE TITLE
WARNING: Error: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

### ISSUE THREAD

**Issue by CrappyText** [asheroto/winget-install#18]
what service do i need to enable for it to be working 
im using RekOs 0.4v
![Capture](https://github.com/asheroto/winget-install/assets/82329147/1ef8924f-feed-4c8e-a3d6-aaf058cfda12)

**Comment by asheroto** [comment]
Looks like you might have an older version of the script. The latest version doesn't have that message. 😊

Run this to confirm...

```powershell
winget-install -CheckForUpdate
```

Then update with this...

https://github.com/asheroto/winget-install#setup

Either way, that appears to be an issue with winget-cli itself, not the installer. This script is just an installer unaffiliated with Microsoft.

Check the troubleshooting section:
https://github.com/asheroto/winget-install#troubleshooting

This issue looks similar:
https://github.com/microsoft/winget-cli/issues/1103
