### ISSUE TITLE
[Feature request]: Initializing winget without rebooting

### ISSUE THREAD

**Issue by uffemcev** [asheroto/winget-install#21]
### What You Are Seeing?

Hello, it's me again! :)
After running the script on a freshly installed system I get this result:

<details><summary>Log</summary>
Checking if winget is installed and working...

ПРЕДУПРЕЖДЕНИЕ: winget is installed but is not detected as a command. Try using winget now. If it doesn't work, wait about 1 minute and try again (it is sometimes delayed). Also try restarting your computer.

ПРЕДУПРЕЖДЕНИЕ: If you restart your computer and the command still isn't recognized, please read the Troubleshooting section
of the README: https://github.com/asheroto/winget-install#troubleshooting

ПРЕДУПРЕЖДЕНИЕ: Make sure you have the latest version of the script by running this command: winget-install -CheckForUpdate

PS C:\Users\uffemcev> winget
winget : Имя "winget" не распознано как имя командлета, функции, файла сценария или выполняемой программы. Проверьте правильность написания имени, а также наличие и правильность пути, после чего повторите попытку.
строка:1 знак:1
\+ winget
\+ ~~~~~~
\+ CategoryInfo          : ObjectNotFound: (winget:String) [], CommandNotFoundException
\+ FullyQualifiedErrorId : CommandNotFoundException
</details>

Even after installation via a script winget is still not initialized in the system. The problem can be solved by restarting the PC, but there is another way to solve this. [Microsoft suggests](https://learn.microsoft.com/en-us/windows/package-manager/winget/) using this command: Add-AppxPackage -RegisterByFamilyName -MainPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe

After this the winget is ready for work instantly. So what do you think about this?

### System Details

Script verson 3.0.1
Windows 22H2
UAC disable
Powershell 5.1
Run as administrator

**Comment by asheroto** [comment]
Hey again!

Just want to confirm... so restarting the computer fixes the issue, yes?

But if we run this command instead, no restart is required?
```
Add-AppxPackage -RegisterByFamilyName -MainPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
```

**Comment by uffemcev** [comment]
Yes it is.

**Comment by asheroto** [comment]
Cool. Have you confirmed this works on your end? Meaning have you run the command yourself and seen winget start working afterwards?

If on Windows 10 I can have it execute that command and then that should ensure winget runs.

**Comment by uffemcev** [comment]
Yes exactly. Now I will reinstall the system again and upload the full log.

**Comment by uffemcev** [comment]
Sorry for russian language in logs.

<details><summary>Log</summary>
Windows PowerShell
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Установите последнюю версию PowerShell для новых функций и улучшения! https://aka.ms/PSWindows

PS C:\Users\uffemcev> winget
winget : Имя "winget" не распознано как имя командлета, функции, файла сценария или выполняемой программы. Проверьте правильность написания имени, а также наличие и правильность пути, после чего повторите попытку.
строка:1 знак:1
\+ winget
\+ ~~~~~~
\+ CategoryInfo          : ObjectNotFound: (winget:String) [], CommandNotFoundException
\+FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\uffemcev> &([ScriptBlock]::Create((irm https://raw.githubusercontent.com/asheroto/winget-install/master/winget-install.ps1)))
winget-install 3.0.1
To check for updates, run winget-install -CheckForUpdate
                                                                                                                                                                                                                                             \##########################################                                                                                                                                                                                                   \# Downloading & installing x64 VCLibs... #                                                                                                                                                                                                   \##########################################                                                                                                                                                                                                                                                                                                                                                                                                                                                Installing x64 VCLibs...

VCLibs installed successfully.

\###########################################
\# Downloading & installing x64 UI.Xaml... #
\###########################################

Installing x64 UI.Xaml...
ПРЕДУПРЕЖДЕНИЕ: Error when trying to download or install UI.Xaml. Trying alternate method...

Downloading UI.Xaml...
Extracting...

Installing x64 UI.Xaml...

UI.Xaml installed successfully.

\######################################
\# Downloading & installing winget... #
\######################################

Retrieving download URL for winget from GitHub...
Downloading winget...
Downloading license...

Installing winget...

winget installed successfully.

\#################################################################################################
\# Checking and adding WindowsApps directory to PATH variable for current user if not present... #
\#################################################################################################

Adding PATH variable for Machine...
PATH variable already present for User, skipping.

\##########################
\# Installation complete! #
\##########################

Checking if winget is installed and working...
ПРЕДУПРЕЖДЕНИЕ: winget is installed but is not detected as a command. Try using winget now. If it doesn't work, wait about 1 minute and try again (it is sometimes delayed). Also try restarting your computer.
ПРЕДУПРЕЖДЕНИЕ: If you restart your computer and the command still isn't recognized, please read the Troubleshooting section
of the README: https://github.com/asheroto/winget-install#troubleshooting
ПРЕДУПРЕЖДЕНИЕ: Make sure you have the latest version of the script by running this command: winget-install -CheckForUpdate
PS C:\Users\uffemcev> winget
winget : Имя "winget" не распознано как имя командлета, функции, файла сценария или выполняемой программы. Проверьте правильность написания имени, а также наличие и правильность пути, после чего повторите попытку.
строка:1 знак:1
\+ winget
\+ ~~~~~~
\+ CategoryInfo          : ObjectNotFound: (winget:String) [], CommandNotFoundException
\+ FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\uffemcev> Add-AppxPackage -RegisterByFamilyName -MainPackage Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
PS C:\Users\uffemcev> winget
Диспетчер пакетов Windows версии 1.6.2771
(с) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Программа командной строки winget дает возможность устанавливать приложения и другие пакеты из командной строки.

использование: winget  [<команда>] [<параметры>]

Применимы следующие команды:
  install    Установка указанного пакета
  show       Показывает сведения о пакете
  source     Управление источниками пакетов
  search     Поиск и отображение базовых сведений о пакетах
  list       Отображать установленные пакеты
  upgrade    Отображает и выполняет доступные обновления
  uninstall  Удаление указанного пакета
  hash       Вспомогательное приложение для хэширования файлов установщика
  validate   Утверждает файл манифеста
  settings   Открыть параметры или настроить параметры администратора
  features   Показывает состояние экспериментальных компонентов
  export     Экспортирует список установленных пакетов
  import     Устанавливает все пакеты в файле
  pin        Управление закреплениями пакетов
  configure  Настройка системы в нужное состояние
  download   Скачивание установщика из указанного пакета

Для более подробной информации о конкретной команде передайте ей аргумент справки. [-?]
</details>

**Comment by uffemcev** [comment]
I confirm that this command initializes winget. No reboot is required. No account logout is required.

**Comment by asheroto** [comment]
Excellent. I will take a look at this in the next few days to implement. I appreciate you pointing this out!

**Comment by asheroto** [comment]
Hey there, just added it. You should now see this when running. Can you please confirm this works in version `3.0.2`?

![image](https://github.com/asheroto/winget-install/assets/49938263/b9954cf9-d58c-49ef-87e2-380198bee8d7)

**Comment by uffemcev** [comment]
Hello! Thanks for this, but this command works in Windows 11 too, my system is 11, not 10.

**Comment by uffemcev** [comment]
Perhaps it makes sense to check not only for 10, but also for 11.

**Comment by asheroto** [comment]
Ah understood. I've got it fixed in version `3.1.1`.

Also I added this method of use:
https://github.com/asheroto/winget-install#method-2---one-line-command-runs-immediately

**Comment by asheroto** [comment]
Going to close this issue, let me know if you think we need to reopen it. I think it should be working now for you on all OS versions.

**Comment by uffemcev** [comment]
I see the changes, thank you very much!

**Comment by asheroto** [comment]
Thanks for letting me know about that, it should help others!
