### ISSUE TITLE
[Bug]: default terminal application and powershell x86 issue

### ISSUE THREAD

**Issue by uffemcev** [asheroto/winget-install#27]
### What You Are Seeing?

Another day - another bug :)

If i set default terminal application as windows terminal and run windows powershell (x86) so `Get-CurrentProcessModuleName` function will stop working because `MainModule` and `Modules` fields are empty. Is it the same for you?

I think function must check several properties at once, but not only `MainModule`.

<details><summary>bug example</summary>

```
Windows PowerShell
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

Установите последнюю версию PowerShell для новых функций и улучшения! https://aka.ms/PSWindows

PS C:\Users\uffemcev> function Get-CurrentProcessModuleName {
>>     <#
>>         .SYNOPSIS
>>             Gets the module name of the current PowerShell process.
>>
>>         .DESCRIPTION
>>             This function retrieves the window title of the current PowerShell host, finds the corresponding process, and returns the name of the main module of that process without the file extension.
>>
>>         .EXAMPLE
>>             $processName = Get-CurrentProcessModuleName
>>             This example shows how to use the function to get the module name of the current process and store it in a variable.
>>
>>         .NOTES
>>             This function assumes that the window title is unique to the current PowerShell session. If multiple windows have the same title, the function may not behave as expected.
>>     #>
>>
>>     $windowTitle = $host.ui.RawUI.WindowTitle
>>     $currentProcess = Get-Process | Where-Object { $_.MainWindowTitle -eq $windowTitle }
>>     $moduleNameWithExtension = $currentProcess.MainModule.ModuleName
>>     $moduleNameWithoutExtension = [System.IO.Path]::GetFileNameWithoutExtension($moduleNameWithExtension)
>>     return $moduleNameWithoutExtension
>> }
PS C:\Users\uffemcev> Get-CurrentProcessModuleName

PS C:\Users\uffemcev> $windowTitle = $host.ui.RawUI.WindowTitle
PS C:\Users\uffemcev> $currentProcess = Get-Process | Where-Object { $_.MainWindowTitle -eq $windowTitle }
PS C:\Users\uffemcev> $currentProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    809      43    92712      82484       0,08  11388   1 WindowsTerminal


PS C:\Users\uffemcev> $currentProcess | format-list *


Name                       : WindowsTerminal
Id                         : 11388
PriorityClass              : Normal
FileVersion                :
HandleCount                : 809
WorkingSet                 : 84463616
PagedMemorySize            : 94937088
PrivateMemorySize          : 94937088
VirtualMemorySize          : -1
TotalProcessorTime         : 00:00:00.0937500
SI                         : 1
Handles                    : 809
VM                         : 4294967295
WS                         : 84463616
PM                         : 94937088
NPM                        : 44152
Path                       :
Company                    :
CPU                        : 0,09375
ProductVersion             :
Description                :
Product                    :
__NounName                 : Process
BasePriority               : 8
ExitCode                   :
HasExited                  : False
ExitTime                   :
Handle                     : 3440
SafeHandle                 : Microsoft.Win32.SafeHandles.SafeProcessHandle
MachineName                : .
MainWindowHandle           : 1574456
MainWindowTitle            : Администратор: Windows PowerShell (x86)
MainModule                 :
MaxWorkingSet              : 1413120
MinWorkingSet              : 204800
Modules                    :
```

</details>

### System Details

Script verson 3.2.2
Windows 11 22H2
UAC disable
Powershell 5.1
Run as administrator

**Comment by uffemcev** [comment]
Maybe something like this? If you like it, i can create pull request.

```
function Terminal-Check {
    $windowTitle = $host.ui.RawUI.WindowTitle
    $currentProcess = Get-Process | Where-Object { $_.MainWindowTitle -eq $windowTitle }
    $processMember = get-process | get-member | foreach {($_.Name)}
    $search = $processMember | foreach {$currentProcess.$_} | where {$_ -match "WindowsTerminal"}
    $search -contains "WindowsTerminal"
}
```

**Comment by uffemcev** [comment]
Or something like this...

```
function Process-Check {
    param (
        [Parameter (Mandatory=$true)]
        [string]$Id
    )
    $windowTitle = $host.ui.RawUI.WindowTitle
    $currentProcess = Get-Process | Where-Object { $_.MainWindowTitle -eq $windowTitle }
    $processMember = get-process | get-member | foreach {($_.Name)}
    $Search = $processMember | foreach {$currentProcess.$_} | where {$_ -match $Id}
    $Search -contains $id
}
```

**Comment by uffemcev** [comment]
I just found out that powershell x86 does not recognize the conhost command. Considering all the problems, I think that is no need to change the `Get-CurrentProcessModuleName` function, but to add a check for powershell x86.

**Comment by asheroto** [comment]
What about this?

```powershell
function Get-CurrentProcessModuleName {
    <#
        .SYNOPSIS
            Gets the module name of the current PowerShell process.
        .DESCRIPTION
            This function retrieves the window title of the current PowerShell host, finds the corresponding process, and returns the name of the main module of that process without the file extension.
        .EXAMPLE
            $processName = Get-CurrentProcessModuleName
            This example shows how to use the function to get the module name of the current process and store it in a variable.
        .NOTES
            This function assumes that the window title is unique to the current PowerShell session. If multiple windows have the same title, the function may not behave as expected.
    #>
    $windowTitle = $host.ui.RawUI.WindowTitle
    $currentProcess = Get-Process | Where-Object { $_.MainWindowTitle -eq $windowTitle }
    $moduleNameWithExtension = $currentProcess.MainModule.ModuleName
    $moduleNameWithoutExtension = [System.IO.Path]::GetFileNameWithoutExtension($moduleNameWithExtension)
    return $moduleNameWithoutExtension
}
```

**Comment by asheroto** [comment]
> I just found out that powershell x86 does not recognize the conhost command. I think there is need to add a check for powershell x86 in x64 systems with `[Environment]::Is64BitProcess` and `[Environment]::Is64BitOperatingSystem`. Like that:
> 
> ```
> if ([Environment]::Is64BitOperatingSystem) {
>     if ([Environment]::Is64BitProcess) {
>         Start-Process -FilePath "conhost.exe" -ArgumentList "powershell -ExecutionPolicy Bypass -Command &{$command}" -Verb RunAs
>     } else {
>         Start-Process -FilePath "$env:windir\sysnative\conhost.exe" -ArgumentList "powershell -ExecutionPolicy Bypass -Command &{$command}" -Verb RunAs
>     }
> } else {
>     Start-Process -FilePath "conhost.exe" -ArgumentList "powershell -ExecutionPolicy Bypass -Command &{$command}" -Verb RunAs
> }
> ```
> 
> [More about sysnative](https://stackoverflow.com/questions/19055924/how-to-launch-64-bit-powershell-from-32-bit-cmd-exe) [More about conhost issue](https://stackoverflow.com/questions/76170073/could-not-find-file-c-windows-system32-conhost-exe)

Looks good, can add that into the main script in your PR.

**Comment by uffemcev** [comment]
>To be same we should probably check against the lowercase name, in case for some reason a version of Windows uses "conhost" instead of "Conhost"

As far as I know, the -match operator is case-insensitive? So $Search -match "Conhost" and $Search -match "conhost" it's same, isn't ?

**Comment by asheroto** [comment]
Oh I'm sorry, I missed that. I program in several languages and forget the characteristics of each.

**Comment by uffemcev** [comment]
> What about this?
> 
> ```powershell
> function Get-CurrentProcessModuleName {
>     <#
>         .SYNOPSIS
>             Gets the module name of the current PowerShell process.
>         .DESCRIPTION
>             This function retrieves the window title of the current PowerShell host, finds the corresponding process, and returns the name of the main module of that process without the file extension.
>         .EXAMPLE
>             $processName = Get-CurrentProcessModuleName
>             This example shows how to use the function to get the module name of the current process and store it in a variable.
>         .NOTES
>             This function assumes that the window title is unique to the current PowerShell session. If multiple windows have the same title, the function may not behave as expected.
>     #>
>     $windowTitle = $host.ui.RawUI.WindowTitle
>     $currentProcess = Get-Process | Where-Object { $_.MainWindowTitle -eq $windowTitle }
>     $moduleNameWithExtension = $currentProcess.MainModule.ModuleName
>     $moduleNameWithoutExtension = [System.IO.Path]::GetFileNameWithoutExtension($moduleNameWithExtension)
>     return $moduleNameWithoutExtension
> }
> ```

Still doesn't work if you run powershell x86 via terminal by default app.
![image](https://github.com/asheroto/winget-install/assets/96709114/3a484a0e-02d5-4c20-8c27-3e17e46d2007)

**Comment by uffemcev** [comment]
It seems I was finally able to correctly identify the process name and id even with many windows open with the same names!

```
function Get-CurrentInterface {
    param (
        [switch]$Name,
        [switch]$Id
    )
    $windowTitle = $host.ui.RawUI.WindowTitle
    $explorerId = (Get-Process -name explorer).id
    $currentProcessParentId = (Get-WmiObject Win32_Process -Filter "ProcessId=$PID").ParentProcessId
    if ($explorerId -eq $currentProcessParentId) {
        $currentInterface = (Get-process -id $pid).Name
    } else {
        $currentInterface = (Get-process -id $currentProcessParentId).Name
    }
    if ($Name) {
        return $currentInterface
    }
    if ($Id) {
        if ($currentInterface -eq "WindowsTerminal") {return $currentProcessParentId} else {return $pid}
    }
}
```

**Comment by uffemcev** [comment]
I need a little more time, then I'll create a pull request.

**Comment by uffemcev** [comment]
Finally a simple and universal solution! :)

```
function Get-CurrentProcess {
    param (
        [switch]$Name,
        [switch]$Id
    )
    $oldTitle = $host.ui.RawUI.WindowTitle
    $TempTitle = (New-Guid).guid
    $host.ui.RawUI.WindowTitle = $TempTitle
    start-sleep 1
    $currentProcess = Get-Process | Where-Object { $_.MainWindowTitle -eq $TempTitle }
    $host.ui.RawUI.WindowTitle = $oldTitle
    if ($Name) {return $currentProcess.Name}
    if ($Id) {return $currentProcess.Id}
}
```

**Comment by uffemcev** [comment]
So, any thoughts?

**Comment by asheroto** [comment]
> So, any thoughts?

I think that will work but I'll have to look tomorrow. It's 3:40 AM here and I've been busy with work so haven't had a chance to look at the PRs closely but will let you know. 😊

**Comment by asheroto** [comment]
that's a pretty clever trick! publishing now thanks for your help
