### ISSUE TITLE
[Request]: -NoExit argument

### ISSUE THREAD

**Issue by uffemcev** [asheroto/winget-install#31]
### Describe the feature or improvement you're requesting

Hello! We know that when restarting in conhost from the terminal with -ForceClose param, the script window automatically closes after completion.

Now I'm see that this behavior exists even in normal mode without a restarting with `-ForceClose` param. So for example this won't work:

<details><summary>test.ps1</summary>

`&([ScriptBlock]::Create((irm https://raw.githubusercontent.com/uffemcev/winget-install/master/winget-install.ps1))) -Force; dir; pause`

</details>

Perhaps it makes sense to add a -`NoExit` param that would disable automatic exit after completion.

Of course, this still probably won't work after restarting from Terminal in Conhost with `-ForceClose` param, but the script warns about this, so it's okay.

**Comment by asheroto** [comment]
This can be done in PowerShell natively? Most scripts don't do this kind of thing. 😊

**Comment by uffemcev** [comment]
I use your script in different cases, in .cmd, in .ps1, in autounattend.xml. Sometimes a script is not launched directly, but through other scripts. Often after the script there are other commands.

During testing, sometimes the window closed before all commands were completed.

Adding the -NoExit functionality would ensure that the script definitely does not close the window after completion.

**Comment by uffemcev** [comment]
> Most scripts don't do this kind of thing. 😊

Yes I know that. I will understand if you decide to decline this request.

**Comment by uffemcev** [comment]
After many tests I figured out what my problem was. If I want to run new commands after the script, I need to run it in a new powershell process:

```
powershell "&([ScriptBlock]::Create((irm asheroto.com/winget))) -Force"
dir
pause
```

So, there is no need for new functionality, sorry for wasting your time! 😅

**Comment by asheroto** [comment]
No worries!

**Comment by asheroto** [comment]
Hello,

FYI the script has been updated to _not_ wait 5-10 seconds at the end. If you need this functionality you can use the `-Wait` parameter and it will restore that function.

😊

Hope all is well!

**Comment by uffemcev** [comment]
Thank you for notification! :)
