### ISSUE TITLE
[Request]: Include Option to Install the PowerShell Module (Microsoft.WinGet.Client)

### ISSUE THREAD

**Issue by norsemangrey** [asheroto/winget-install#35]
### Describe the feature or improvement you're requesting

It would be nice to include an option to also install the WinGet PowerShell module (Microsoft.WinGet.Client) after WinGet is installed.

**Comment by asheroto** [comment]
Hello,

How do you install Microsoft.WinGet.Client?

**Comment by norsemangrey** [comment]
It can be installed from PSGallery using `Module-Install -Name
Microsoft.WinGet.Client`

**Comment by asheroto** [comment]
Hello,

Do you mean `Install-Module -Name Microsoft.WinGet.Client`?

I'm having trouble understanding why you think it should be integrated into this script? Can't you just run it as soon after `winget` is installed? Maybe I'm missing something.

**Comment by norsemangrey** [comment]
Yes, sorry...fast typing on the phone :) 

I would just be nice to have it set up automatically with the rest of the script instead of having to install it manually later.

**Comment by asheroto** [comment]
Hello,

I understand. It's outside the scope of this project, but we may consider it in the future.

Thank you.
