### ISSUE TITLE
[Bug]: Fails during Registering step

### ISSUE THREAD

**Issue by MiketheMaker18** [asheroto/winget-install#38]
### Checklist

- [X] I have performed the steps in the [Troubleshooting](https://github.com/asheroto/winget-install#troubleshooting) section and confirm that the issue only occurs with this script.
- [X] I have restarted my computer to confirm this is not a transitory problem.

- [X] I have verified that I am using the latest version of winget-install.

- [X] I have verified that this issue is NOT security related (please create [security advisory](https://github.com/asheroto/winget-install/security/advisories) if so).

- [X] I have run the script with the `-DebugMode` argument and included the output below

###############
# Registering #
###############

```
Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict validation.
Windows cannot install package Microsoft.DesktopAppInstaller_1.22.10582.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework
"Microsoft.UI.Xaml.2.8" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version
8.2310.30001.0, along with this package to install. The frameworks with name "Microsoft.UI.Xaml.2.8" currently installed are: {}
NOTE: For additional information, look for [ActivityId] f6859c66-6b2d-0006-36da-85f62d6bda01 in the Event Log or use the command line Get-AppPackageLog -ActivityID
f6859c66-6b2d-0006-36da-85f62d6bda01
At C:\Program Files\WindowsPowerShell\Scripts\winget-install.ps1:829 char:13
+             Add-AppxPackage -RegisterByFamilyName -MainPackage Micros ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Deskt...r_8wekyb3d8bbwe:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageComman
```

### System Details

Windows 10 Pro x64 22H2

### Additional Context

Just started 2/27/24.

### Full Output With `-DebugMode`

`Name                           Value
----                           -----
PSVersion                      5.1.19041.3803
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3803
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Name             : ConsoleHost
Version          : 5.1.19041.3803
InstanceId       : 6b9ff3ac-41c9-49c1-be6b-d61ef09a6d4a
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

winget-install 4.0.2
To check for updates, run winget-install -CheckForUpdate
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_OperatingSystem'.
VERBOSE: Operation 'Enumerate CimInstances' complete.

#################
# Prerequisites #
#################

Downloading VCLibs...
VERBOSE: GET https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx with 0-byte payload
VERBOSE: received 6764349-byte response of content type application/octet-stream
Downloading UI.Xaml...
VERBOSE: GET https://github.com/microsoft/microsoft-ui-xaml/releases/download/v2.7.3/Microsoft.UI.Xaml.2.7.x64.appx with 0-byte payload
VERBOSE: received 5070706-byte response of content type application/octet-stream

##########
# winget #
##########

VERBOSE: GET https://api.github.com/repos/microsoft/winget-cli/releases with 0-byte payload
VERBOSE: received 449422-byte response of content type application/json; charset=utf-8
Downloading winget license...
VERBOSE: GET https://github.com/microsoft/winget-cli/releases/download/v1.7.10582/5e4a105df01840b0bbf00985e4f57c1e_License1.xml with 0-byte payload
VERBOSE: received 2688-byte response of content type application/octet-stream
Downloading winget...
VERBOSE: GET https://aka.ms/getwinget with 0-byte payload
VERBOSE: received 258178004-byte response of content type application/octet-stream
Installing winget and its dependencies...
VERBOSE: Target Image Version 10.0.19045.3803

############
# Complete #
############

winget installed successfully.
Checking if winget is installed and working...

###############
# Registering #
###############

Add-AppxPackage : Deployment failed with HRESULT: 0x80073CF3, Package failed updates, dependency or conflict validation.
Windows cannot install package Microsoft.DesktopAppInstaller_1.22.10582.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework
"Microsoft.UI.Xaml.2.8" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version
8.2310.30001.0, along with this package to install. The frameworks with name "Microsoft.UI.Xaml.2.8" currently installed are: {}
NOTE: For additional information, look for [ActivityId] f6859c66-6b2d-0006-07de-85f62d6bda01 in the Event Log or use the command line Get-AppPackageLog -ActivityID
f6859c66-6b2d-0006-07de-85f62d6bda01
At C:\Program Files\WindowsPowerShell\Scripts\winget-install.ps1:829 char:13
+             Add-AppxPackage -RegisterByFamilyName -MainPackage Micros ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (Microsoft.Deskt...r_8wekyb3d8bbwe:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

VERBOSE: Operation completed for: Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
winget command registered successfully.`

**Comment by MiketheMaker18** [comment]
Sorry, found this afterwards. It's an issue with winget-cli:
[Issue 4208](https://github.com/microsoft/winget-cli/issues/4208 )

**Comment by asheroto** [comment]
You did all the hard work for me! Ha! Thanks so much for reporting this. Releasing an updated version now.
