### ISSUE TITLE
[Bug]: Get-OSInfo incorrectly identifies Windows 11 23H2 Multi-Session as a Server OS < 2022

### ISSUE THREAD

**Issue by pyasuda** [asheroto/winget-install#39]
### Checklist

- [X] I have performed the steps in the [Troubleshooting](https://github.com/asheroto/winget-install#troubleshooting) section and confirm that the issue only occurs with this script.
- [X] I have restarted my computer to confirm this is not a transitory problem.

- [X] I have verified that I am using the latest version of winget-install.

- [X] I have verified that this issue is NOT security related (please create [security advisory](https://github.com/asheroto/winget-install/security/advisories) if so).

- [X] I have run the script with the `-DebugMode` argument and included the output below

### What You Are Seeing?

Running the script on Windows 11 23H2 Enterprise multi-session (for Azure Virtual Desktop) Azure Marketplace image. The script returns this error: 

winget requires Windows Server 2022 or newer on server platforms. Your version of Windows Server is not supported.

Running with -Force or -Debug returns same error. 

I think the problem is the EditionID is ServerRdsh. 

### System Details

Azure Marketplace image: 
Windows 11 (23H2) Enterprise multi-session + Microsoft 365 Apps - Gen2 (multi-session)
February Windows update installed
See Additional Context for details

### Additional Context

PS C:\> $osDetails = Get-CimInstance -ClassName Win32_OperatingSystem
PS C:\> $osDetails
SystemDirectory     Organization BuildNumber RegisteredUser SerialNumber            Version
---------------     ------------ ----------- -------------- ------------            -------
C:\Windows\system32              22631                      00432-70000-00001-AA416 10.0.22631

PS C:\> Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion"
SystemRoot                : C:\Windows
BaseBuildRevisionNumber   : 1
BuildBranch               : ni_release
BuildGUID                 : ffffffff-ffff-ffff-ffff-ffffffffffff
BuildLab                  : 22621.ni_release.220506-1250
BuildLabEx                : 22621.1.amd64fre.ni_release.220506-1250
CompositionEditionID      : Enterprise
CurrentBuild              : 22631
CurrentBuildNumber        : 22631
CurrentMajorVersionNumber : 10
CurrentMinorVersionNumber : 0
CurrentType               : Multiprocessor Free
CurrentVersion            : 6.3
DisplayVersion            : 23H2
EditionID                 : ServerRdsh
EditionSubManufacturer    :
EditionSubstring          :
EditionSubVersion         :
InstallationType          : Client
InstallDate               : 1709571506
ProductName               : Windows 10 Enterprise multi-session
ReleaseId                 : 2009
SoftwareType              : System
UBR                       : 3155
PathName                  : C:\Windows
PendingInstall            : 0
ProductId                 : 00432-70000-00001-AA416
DigitalProductId          : {164, 0, 0, 0...}
DigitalProductId4         : {248, 4, 0, 0...}
InstallTime               : 133540451065555457
PSPath                    : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows
                            NT\CurrentVersion
PSParentPath              : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT
PSChildName               : CurrentVersion
PSDrive                   : HKLM
PSProvider                : Microsoft.PowerShell.Core\Registry

**Comment by asheroto** [comment]
Interesting! Thanks for reporting.

Can you run this on the system? I'm guessing it says 2 or 3?

```
(Get-CimInstance -ClassName Win32_OperatingSystem).ProductType
```

**Comment by asheroto** [comment]
Also can you please run this?

```
(Get-CimInstance -ClassName Win32_OperatingSystem).Caption
```

**Comment by pyasuda** [comment]
PS C:\> (Get-CimInstance -ClassName Win32_OperatingSystem).ProductType
3
PS C:\> (Get-CimInstance -ClassName Win32_OperatingSystem).Caption
Microsoft Windows 11 Enterprise multi-session


As you said, 3.

**Comment by pyasuda** [comment]
I was able to get the script to work in a really ugly way: I inserted this before the server OS version check: 

$osVersion.NumericVersion = "2022"

I also failed to mention that for some unknown reason the Azure Marketplace image comes with Winget 1.2.

**Comment by asheroto** [comment]
Okay, so the `ProductType` is 3, which means server, but the caption says "Windows 11", which is a workstation. [More info](https://learn.microsoft.com/en-us/dotnet/api/microsoft.powershell.commands.producttype?view=powershellsdk-1.1.0)

So I added [another check](https://github.com/asheroto/winget-install/blob/1ef855b373b327086424cfea592629a1ed82e594/winget-install.ps1#L199-L202) if the OS numeric value is 10 or greater, and the caption contains the phrase "multi-session" in the caption, consider it a workstation.

Run this and see if it works. If for some reason it won't let you run it, go to the URL in the command, download the file, then run it locally.

```powershell
&([ScriptBlock]::Create((irm https://raw.githubusercontent.com/asheroto/winget-install/Multi-Session-Test/winget-install.ps1))) -Force
```

**Comment by pyasuda** [comment]
Thank you. I'm deploying a new VM to test.

**Comment by pyasuda** [comment]
Happy to report success. Verified these on the test VM: 
PS C:> (Get-CimInstance -ClassName Win32_OperatingSystem).ProductType
3
PS C:> (Get-CimInstance -ClassName Win32_OperatingSystem).Caption
Microsoft Windows 11 Enterprise multi-session

Verified winget -v showed v1.2.10691 

After running the command as given, winget -v showed v1.7.10582
Ran winget install Microsoft.PowerShell
pwsh 7.4.1 installed

Thank you! Will that test URL remain available?

**Comment by asheroto** [comment]
Okay great!

The URL will stay active until later this evening when I publish the release to the master branch. After that I'll delete the multi-session test branch and that particular URL won't work anymore. But the main script will include the fix at that time.

**Comment by asheroto** [comment]
Version `4.0.4` has been released which fixes this issue. Thanks again!

**Comment by pyasuda** [comment]
Thank you! This script is a big help with our AVD automation.
