### ISSUE TITLE
[Request]: 2019 don't install VSRedist if already installed

### ISSUE THREAD

**Issue by o-l-a-v** [asheroto/winget-install#44]
### Describe the feature or improvement you're requesting

For Windows Server 2019: Don't download and install VCRedist if already installed.

<https://github.com/asheroto/winget-install/blob/958f61fde5291c35943e0236895e49aafa99637d/winget-install.ps1#L872-L890>

### Additional context

Some ways to detect whether required VCRedist is installed:

```powershell
# Assets
$64BitOS = [System.Environment]::Is64BitOperatingSystem
$64BitProcess = [System.Environment]::Is64BitProcess

# Require running system native process
if ($64BitOS -and -not $64BitProcess) {
    Throw 'Please run PowerShell in the systen native architecture (x64 PowerShell if x64 Windows).'
}

# Check that uninstall information exists in the registry
Test-Path -Path (
    [string]::Format(
        'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\{0}\Microsoft\VisualStudio\14.0\VC\Runtimes\X{1}',
        $(if($64BitOS -and $64BitProcess){'WOW6432Node\'}),
        $(if($64BitOS){'64'}else{'86'})
    )
)

# Check that one required DLL exists on the file system
[System.IO.File]::Exists(
    [string]::Format(
        '{0}\system32\concrt140.dll',
        $env:windir
    )
)
```

I've done something similar with my WinGet + Intune R'n'D project:

* <https://github.com/o-l-a-v/winget-intune-win32/blob/main/Prerequirement%20-%20VCRedist%202015-2022/Microsoft%20VCRedist%202015-2022%20-%20Install%20parameters.md>

**Comment by asheroto** [comment]
This is excellent! Adding it in `4.1.1`. Thanks!

**Comment by asheroto** [comment]
Gave you credit at the top. 😊 Will be releasing a new version soon.

https://github.com/asheroto/winget-install/blob/master/winget-install.ps1
