### ISSUE TITLE
[Bug]: does arm64 is supported?

### ISSUE THREAD

**Issue by emmanuelpare** [asheroto/winget-install#46]
### Checklist

- [X] I have give this issue a title starting with the text `[Bug]:` to signify it is a bug.
- [X] I have performed the steps in the [Troubleshooting](https://github.com/asheroto/winget-install#troubleshooting) section and confirm that the issue only occurs with this script.
- [X] I have restarted my computer to confirm this is not a transitory problem.

- [X] I have verified that I am using the latest version of winget-install.

- [X] I have verified that this issue is NOT security related (please create [security advisory](https://github.com/asheroto/winget-install/security/advisories) if so).

- [X] I have run the script with the `-Debug` argument and included the output below

### What You Are Seeing?

Hi,

In the Get-OsInfo function, I don’t see a check for ARM64. For example:

elseif (($osDetails.OSArchitecture).StartsWith("ARM")) {
    $architecture = "arm64"
}

I think this is needed to install the correct binary where you are using $arch.

### System Details

windows 11 arm64

**Comment by asheroto** [comment]
Hello,

On an arm64 system, this line should take care of it.

https://github.com/asheroto/winget-install/blob/b9b12f69e9e16f19262e690be96b549c5252cbd7/winget-install.ps1#L179

The other lines like this...

https://github.com/asheroto/winget-install/blob/b9b12f69e9e16f19262e690be96b549c5252cbd7/winget-install.ps1#L181-L186

Should actually just replace the values from the architecture variable.

Can you replicate this on your end though to confirm?

**Comment by emmanuelpare** [comment]
Update: OK: I got it fixed by Installing. VC_Redis  https://aka.ms/vs/17/release/vc_redist.arm64.exe

**Comment by asheroto** [comment]
Ah okay, good to know, though!

Glad you got it working!
